// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/v1/proto.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RepoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoRequest) Reset() {
	*x = RepoRequest{}
	mi := &file_api_v1_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoRequest) ProtoMessage() {}

func (x *RepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoRequest.ProtoReflect.Descriptor instead.
func (*RepoRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_proto_rawDescGZIP(), []int{0}
}

func (x *RepoRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RepoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RepoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fullname      string                 `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	ForksCount    int32                  `protobuf:"varint,3,opt,name=forks_count,json=forksCount,proto3" json:"forks_count,omitempty"`
	StarsCount    int32                  `protobuf:"varint,4,opt,name=stars_count,json=starsCount,proto3" json:"stars_count,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoReply) Reset() {
	*x = RepoReply{}
	mi := &file_api_v1_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoReply) ProtoMessage() {}

func (x *RepoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoReply.ProtoReflect.Descriptor instead.
func (*RepoReply) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_proto_rawDescGZIP(), []int{1}
}

func (x *RepoReply) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *RepoReply) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *RepoReply) GetForksCount() int32 {
	if x != nil {
		return x.ForksCount
	}
	return 0
}

func (x *RepoReply) GetStarsCount() int32 {
	if x != nil {
		return x.StarsCount
	}
	return 0
}

func (x *RepoReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_api_v1_proto_proto protoreflect.FileDescriptor

const file_api_v1_proto_proto_rawDesc = "" +
	"\n" +
	"\x12api/v1/proto.proto\x12\x06api.v1\"7\n" +
	"\vRepoRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x9c\x01\n" +
	"\tRepoReply\x12\x1a\n" +
	"\bfullname\x18\x01 \x01(\tR\bfullname\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\x12\x1f\n" +
	"\vforks_count\x18\x03 \x01(\x05R\n" +
	"forksCount\x12\x1f\n" +
	"\vstars_count\x18\x04 \x01(\x05R\n" +
	"starsCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt2D\n" +
	"\tCollector\x127\n" +
	"\vGetRepoData\x12\x13.api.v1.RepoRequest\x1a\x11.api.v1.RepoReply\"\x00B7Z5github.com/Danil-Zaripov/golang-course/project/api/v1b\x06proto3"

var (
	file_api_v1_proto_proto_rawDescOnce sync.Once
	file_api_v1_proto_proto_rawDescData []byte
)

func file_api_v1_proto_proto_rawDescGZIP() []byte {
	file_api_v1_proto_proto_rawDescOnce.Do(func() {
		file_api_v1_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_proto_proto_rawDesc), len(file_api_v1_proto_proto_rawDesc)))
	})
	return file_api_v1_proto_proto_rawDescData
}

var file_api_v1_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_proto_proto_goTypes = []any{
	(*RepoRequest)(nil), // 0: api.v1.RepoRequest
	(*RepoReply)(nil),   // 1: api.v1.RepoReply
}
var file_api_v1_proto_proto_depIdxs = []int32{
	0, // 0: api.v1.Collector.GetRepoData:input_type -> api.v1.RepoRequest
	1, // 1: api.v1.Collector.GetRepoData:output_type -> api.v1.RepoReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_proto_proto_init() }
func file_api_v1_proto_proto_init() {
	if File_api_v1_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_proto_proto_rawDesc), len(file_api_v1_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_proto_proto_goTypes,
		DependencyIndexes: file_api_v1_proto_proto_depIdxs,
		MessageInfos:      file_api_v1_proto_proto_msgTypes,
	}.Build()
	File_api_v1_proto_proto = out.File
	file_api_v1_proto_proto_goTypes = nil
	file_api_v1_proto_proto_depIdxs = nil
}
